services:
  - type: web
    name: bakery-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://preetamdivakar:bu6sphE4pv5YwioC@cluster0.nazwmop.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
